name: example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_extendable_annotation:
    path: ../enum_extendable_annotation

dev_dependencies:
  build_runner: ^2.1.0
  enum_extendable_generator:
    path: ../enum_extendable_generator
  test: ^1.16.0
