name: enum_extendable_generator
version: 0.1.1
description: >-
  Allows you to add fields and methods to enums. Generates code for extensions on enums.
repository: https://github.com/OlehVedernikov/enum_extendable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  build_config: ^1.0.0
  source_gen: ^1.1.1
  collection: ^1.15.0

  enum_extendable_annotation: ^0.1.1
